### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by sskras** [Ameobea/spotifytrack#34]
@Ameobea, on Sep 6, 2021 you changed license from BOML to MIT:

https://github.com/Ameobea/spotifytrack/commit/bab716c572c5d3fc32bda7976719648d65594b1e#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7

May I know the idea behind this change, please:)?

**Comment by Ameobea** [comment]
Hi, I changed the license because nobody is familiar with the blue oak license and it seems to not be used anywhere.  NPM doesn't recognize it, Github doesn't (or at least didn't at the time) recognize it, etc.

They're both very permissive licenses which grant pretty much the same things as far as I can tell.  I don't think the license mattters much for this project anyway, though.

**Comment by sskras** [comment]
Thanks for the details!

Yes, GitHub still does not recognize it, but for that to happen it needs around 1000 GitHub projects to be using it (and then some other things):
https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license

To track that I compiled a list of repos:
https://github.com/sskras/license-test/blob/master/repo-list-using-blueoak.md#the-main-list

... and this repo is one of those that shrunk the list : P

No offence, just wanted some clarity. Cheers!
